package fdoshared

type CONFIG_ENTRY string

const (
	CFG_API_KEY_RESULTS CONFIG_ENTRY = "RESULTS_API_KEY"
	CFG_API_BUILDS_URL  CONFIG_ENTRY = "BUILDS_API_URL"
	CFG_FDO_SERVICE_URL CONFIG_ENTRY = "FDO_SERVICE_URL"
	CFG_MODE            CONFIG_ENTRY = "MODE"
)

type CONFIG_MODE_TYPE string

const (
	CFG_MODE_ONPREM CONFIG_MODE_TYPE = "onprem"
	CFG_MODE_ONLINE CONFIG_MODE_TYPE = "online"
)
