package fdoshared

type CONFIG_ENTRY string

const (
	CFG_ENV_API_KEY_RESULTS CONFIG_ENTRY = "RESULTS_API_KEY"
	CFG_ENV_API_BUILDS_URL  CONFIG_ENTRY = "BUILDS_API_URL"
	CFG_ENV_FDO_SERVICE_URL CONFIG_ENTRY = "FDO_SERVICE_URL"
	CFG_ENV_MODE            CONFIG_ENTRY = "MODE"
)

const (
	CFG_MODE_ONPREM string = "onprem"
	CFG_MODE_ONLINE string = "online"
)
