package fdoshared

type CONFIG_ENTRY string

const (
	CFG_ENV_FDO_SERVICE_URL CONFIG_ENTRY = "FDO_SERVICE_URL"
	CFG_ENV_MODE            CONFIG_ENTRY = "MODE"

	CFG_DEV_ENV  CONFIG_ENTRY = "DEV"
	CFG_ENV_PORT CONFIG_ENTRY = "PORT"

	// For conformance testing
	CFG_ENV_INTEROP_ENABLED            CONFIG_ENTRY = "INTEROP_ENABLED"
	CFG_ENV_INTEROP_DASHBOARD_URL      CONFIG_ENTRY = "INTEROP_DASHBOARD_URL"
	CFG_ENV_INTEROP_DASHBOARD_RV_AUTHZ CONFIG_ENTRY = "INTEROP_DASHBOARD_RV_AUTHZ"
	CFG_ENV_INTEROP_DASHBOARD_DO_AUTHZ CONFIG_ENTRY = "INTEROP_DASHBOARD_DO_AUTHZ"
	CFG_ENV_INTEROP_DO_TOKEN_MAPPING   CONFIG_ENTRY = "INTEROP_DO_TOKEN_MAPPING"
)

const (
	CFG_MODE_ONPREM string = "onprem"
	CFG_MODE_ONLINE string = "online"
	CFG_ENV_DEV     string = "dev"
	CFG_ENV_PROD    string = "prod"
)
