package fdoshared

type CONFIG_ENTRY string

const (
	CFG_ENV_API_KEY_RESULTS CONFIG_ENTRY = "RESULTS_API_KEY"
	CFG_ENV_API_BUILDS_URL  CONFIG_ENTRY = "BUILDS_API_URL"
	CFG_ENV_FDO_SERVICE_URL CONFIG_ENTRY = "FDO_SERVICE_URL"
	CFG_ENV_MODE            CONFIG_ENTRY = "MODE"

	CFG_DEV_ENV CONFIG_ENTRY = "DEV"

	CFG_ENV_PORT CONFIG_ENTRY = "PORT"

	CFG_ENV_NOTIFY_SERVICE_HOST   CONFIG_ENTRY = "NOTIFY_SERVICE_HOST"
	CFG_ENV_NOTIFY_SERVICE_SECRET CONFIG_ENTRY = "NOTIFY_SERVICE_SECRET"

	CFG_ENV_GITHUB_CLIENTID     CONFIG_ENTRY = "OAUTH2_GITHUB_CLIENTID"
	CFG_ENV_GITHUB_CLIENTSECRET CONFIG_ENTRY = "OAUTH2_GITHUB_CLIENTSECRET"
	CFG_ENV_GITHUB_REDIRECTURL  CONFIG_ENTRY = "OAUTH2_GITHUB_REDIRECTURL"

	CFG_ENV_GOOGLE_CLIENTID     CONFIG_ENTRY = "OAUTH2_GOOGLE_CLIENTID"
	CFG_ENV_GOOGLE_CLIENTSECRET CONFIG_ENTRY = "OAUTH2_GOOGLE_CLIENTSECRET"
	CFG_ENV_GOOGLE_REDIRECTURL  CONFIG_ENTRY = "OAUTH2_GOOGLE_REDIRECTURL"

	CFG_ENV_MICROSOFT_CLIENTID     CONFIG_ENTRY = "OAUTH2_MICROSOFT_CLIENTID"
	CFG_ENV_MICROSOFT_CLIENTSECRET CONFIG_ENTRY = "OAUTH2_MICROSOFT_CLIENTSECRET"
	CFG_ENV_MICROSOFT_REDIRECTURL  CONFIG_ENTRY = "OAUTH2_MICROSOFT_REDIRECTURL"
)

const (
	CFG_MODE_ONPREM string = "onprem"
	CFG_MODE_ONLINE string = "online"
	CFG_ENV_DEV     string = "dev"
	CFG_ENV_PROD    string = "prod"
)
