package fdoshared

const (
	OWNERSHIP_VOUCHER_PEM_TYPE string = "OWNERSHIP VOUCHER"
	CREDENTIAL_PEM_TYPE        string = "WAW FDO DEVICE CREDENTIAL"
	PRIVATE_KEY_PEM_TYPE       string = "PRIVATE KEY"
)
