package testcom

const (
	FIDO_LISTENER_POSITIVE FDOTestID = "FIDO_LISTENER_POSITIVE"
	// 30
	FIDO_LISTENER_DEVICE_30_BAD_ENCODING FDOTestID = "FIDO_LISTENER_DEVICE_30_BAD_ENCODING"

	// 32
	FIDO_LISTENER_DEVICE_32_BAD_ENCODING FDOTestID = "FIDO_LISTENER_DEVICE_32_BAD_ENCODING"
	FIDO_LISTENER_DEVICE_32_BAD_TO1D     FDOTestID = "FIDO_LISTENER_DEVICE_32_BAD_TO1D"
)

// RV
var FIDO_LISTENER_20_LIST []FDOTestID = []FDOTestID{}

var FIDO_LISTENER_22_LIST []FDOTestID = []FDOTestID{}

// RV
var FIDO_LISTENER_30_LIST []FDOTestID = []FDOTestID{
	FIDO_LISTENER_DEVICE_30_BAD_ENCODING,
}

var FIDO_LISTENER_32_LIST []FDOTestID = []FDOTestID{
	FIDO_LISTENER_DEVICE_32_BAD_ENCODING,
	FIDO_LISTENER_DEVICE_32_BAD_TO1D,
}

// DO
var FIDO_LISTENER_60_LIST []FDOTestID = []FDOTestID{}

var FIDO_LISTENER_62_LIST []FDOTestID = []FDOTestID{}

var FIDO_LISTENER_64_LIST []FDOTestID = []FDOTestID{}

var FIDO_LISTENER_66_LIST []FDOTestID = []FDOTestID{}

var FIDO_LISTENER_68_LIST []FDOTestID = []FDOTestID{}

var FIDO_LISTENER_70_LIST []FDOTestID = []FDOTestID{}
