package testcom

const (
	FIDO_LISTENER_POSITIVE FDOTestID = "FIDO_LISTENER_POSITIVE"
	// 30
	FIDO_LISTENER_DEVICE_30_BAD_ENCODING FDOTestID = "FIDO_LISTENER_DEVICE_30_BAD_ENCODING"

	// 32
	FIDO_LISTENER_DEVICE_32_BAD_ENCODING FDOTestID = "FIDO_LISTENER_DEVICE_32_BAD_ENCODING"
	FIDO_LISTENER_DEVICE_32_BAD_TO1D     FDOTestID = "FIDO_LISTENER_DEVICE_32_BAD_TO1D"
)

// RV
var FIDO_LISTENER_20_LIST []FDOTestID = []FDOTestID{}

var FIDO_LISTENER_22_LIST []FDOTestID = []FDOTestID{}

// RV
var FIDO_LISTENER_30_LIST []FDOTestID = []FDOTestID{
	FIDO_LISTENER_DEVICE_30_BAD_ENCODING,
}

var FIDO_LISTENER_32_LIST []FDOTestID = []FDOTestID{
	FIDO_LISTENER_DEVICE_32_BAD_ENCODING,
	FIDO_LISTENER_DEVICE_32_BAD_TO1D,
}

// DO

const (
	// 60
	FIDO_LISTENER_DEVICE_60_BAD_OVHDR_OVHEADER            FDOTestID = "FIDO_LISTENER_DEVICE_60_BAD_OVHDR_OVHEADER"
	FIDO_LISTENER_DEVICE_60_BAD_NONCE_TO2PROVEOV          FDOTestID = "FIDO_LISTENER_DEVICE_60_BAD_NONCE_TO2PROVEOV"
	FIDO_LISTENER_DEVICE_60_BAD_EBSIGNINFO                FDOTestID = "FIDO_LISTENER_DEVICE_60_BAD_EBSIGNINFO"
	FIDO_LISTENER_DEVICE_60_BAD_HELLODEVICEHASH           FDOTestID = "FIDO_LISTENER_DEVICE_60_BAD_HELLODEVICEHASH"
	FIDO_LISTENER_DEVICE_60_BAD_COSE_SIGNATURE            FDOTestID = "FIDO_LISTENER_DEVICE_60_BAD_COSE_SIGNATURE"
	FIDO_LISTENER_DEVICE_60_BAD_HELLOACK_PAYLOAD_ENCODING FDOTestID = "FIDO_LISTENER_DEVICE_60_BAD_HELLOACK_PAYLOAD_ENCODING"
	FIDO_LISTENER_DEVICE_60_BAD_HELLOACK_ENCODING         FDOTestID = "FIDO_LISTENER_DEVICE_60_BAD_HELLOACK_ENCODING"
	FIDO_LISTENER_DEVICE_60_MISSING_AUTHZ_HEADER          FDOTestID = "FIDO_LISTENER_DEVICE_60_MISSING_AUTHZ_HEADER"

	// 62
	FIDO_LISTENER_DEVICE_62_BAD_OVENTRY_COSE_SIGNATURE FDOTestID = "FIDO_LISTENER_DEVICE_62_BAD_OVENTRY_COSE_SIGNATURE"
	FIDO_LISTENER_DEVICE_62_BAD_OVNEXTENTRY_PAYLOAD    FDOTestID = "FIDO_LISTENER_DEVICE_62_BAD_OVNEXTENTRY_PAYLOAD"
	FIDO_LISTENER_DEVICE_62_BAD_OVENTRYNUM             FDOTestID = "FIDO_LISTENER_DEVICE_62_BAD_OVENTRYNUM"

	// 64
	FIDO_LISTENER_DEVICE_64_BAD_OVENTRYNUM                 FDOTestID = "FIDO_LISTENER_DEVICE_64_BAD_OVENTRYNUM"
	FIDO_LISTENER_DEVICE_64_BAD_NONCE_TO2SETUPDV           FDOTestID = "FIDO_LISTENER_DEVICE_64_BAD_NONCE_TO2SETUPDV"
	FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_PAYLOAD        FDOTestID = "FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_PAYLOAD"
	FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_COSE_SIGNATURE FDOTestID = "FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_COSE_SIGNATURE"
	FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_BYTES          FDOTestID = "FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_BYTES"
	FIDO_LISTENER_DEVICE_64_BAD_ENC_WRAPPING               FDOTestID = "FIDO_LISTENER_DEVICE_64_BAD_ENC_WRAPPING"
	FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_ENCODING       FDOTestID = "FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_ENCODING"

	// 66
	FIDO_LISTENER_DEVICE_66_BAD_ENCODING     FDOTestID = "FIDO_LISTENER_DEVICE_66_BAD_ENCODING"
	FIDO_LISTENER_DEVICE_66_BAD_ENC_WRAPPING FDOTestID = "FIDO_LISTENER_DEVICE_66_BAD_ENC_WRAPPING"

	// 70
	FIDO_LISTENER_DEVICE_70_BAD_NONCE_TO2SETUPDV64 FDOTestID = "FIDO_LISTENER_DEVICE_70_BAD_NONCE_TO2SETUPDV64"
	FIDO_LISTENER_DEVICE_70_BAD_DONE71_ENCODING    FDOTestID = "FIDO_LISTENER_DEVICE_70_BAD_DONE71_ENCODING"
	FIDO_LISTENER_DEVICE_70_BAD_ENC_WRAPPING       FDOTestID = "FIDO_LISTENER_DEVICE_70_BAD_ENC_WRAPPING"
)

var FIDO_LISTENER_60_LIST []FDOTestID = []FDOTestID{
	FIDO_LISTENER_DEVICE_60_BAD_OVHDR_OVHEADER,
	FIDO_LISTENER_DEVICE_60_BAD_NONCE_TO2PROVEOV,
	FIDO_LISTENER_DEVICE_60_BAD_EBSIGNINFO,
	FIDO_LISTENER_DEVICE_60_BAD_HELLODEVICEHASH,
	FIDO_LISTENER_DEVICE_60_BAD_COSE_SIGNATURE,
	FIDO_LISTENER_DEVICE_60_BAD_HELLOACK_PAYLOAD_ENCODING,
	FIDO_LISTENER_DEVICE_60_BAD_HELLOACK_ENCODING,
	FIDO_LISTENER_DEVICE_60_MISSING_AUTHZ_HEADER,
}

var FIDO_LISTENER_62_LIST []FDOTestID = []FDOTestID{
	FIDO_LISTENER_DEVICE_62_BAD_OVENTRY_COSE_SIGNATURE,
	FIDO_LISTENER_DEVICE_62_BAD_OVNEXTENTRY_PAYLOAD,
	FIDO_LISTENER_DEVICE_62_BAD_OVENTRYNUM,
}

var FIDO_LISTENER_64_LIST []FDOTestID = []FDOTestID{
	FIDO_LISTENER_DEVICE_64_BAD_OVENTRYNUM,
	FIDO_LISTENER_DEVICE_64_BAD_NONCE_TO2SETUPDV,
	FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_PAYLOAD,
	FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_COSE_SIGNATURE,
	FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_BYTES,
	FIDO_LISTENER_DEVICE_64_BAD_ENC_WRAPPING,
	FIDO_LISTENER_DEVICE_64_BAD_SETUPDEVICE_ENCODING,
}

var FIDO_LISTENER_66_LIST []FDOTestID = []FDOTestID{
	FIDO_LISTENER_DEVICE_66_BAD_ENCODING,
	FIDO_LISTENER_DEVICE_66_BAD_ENC_WRAPPING,
}

var FIDO_LISTENER_68_LIST []FDOTestID = []FDOTestID{}

var FIDO_LISTENER_70_LIST []FDOTestID = []FDOTestID{
	FIDO_LISTENER_DEVICE_70_BAD_NONCE_TO2SETUPDV64,
	FIDO_LISTENER_DEVICE_70_BAD_DONE71_ENCODING,
	FIDO_LISTENER_DEVICE_70_BAD_ENC_WRAPPING,
}
