package testcom

type FDOTestID string

const (
	FIDO_RVT_20_BAD_ENCODING FDOTestID = "FIDO_RVT_20_BAD_ENCODING"
	FIDO_RVT_20_POSITIVE     FDOTestID = "FIDO_RVT_20_POSITIVE"
	FIDO_RVT_21_CHECK_RESP   FDOTestID = "FIDO_RVT_21_CHECK_RESP"

	FIDO_RVT_22_BAD_ENCODING                   FDOTestID = "FIDO_RVT_22_BAD_ENCODING"
	FIDO_RVT_22_BAD_SIGNATURE                  FDOTestID = "FIDO_RVT_22_BAD_SIGNATURE"
	FIDO_RVT_22_BAD_SIGNATURE_NOT_MATCHING_ALG FDOTestID = "FIDO_RVT_22_BAD_SIGNATURE_NOT_MATCHING_ALG"

	FIDO_RVT_23_CHECK_RESP FDOTestID = "FIDO_RVT_23_CHECK_RESP"

	FIDO_RVT_22_BAD_TO0D_HASH FDOTestID = "FIDO_RVT_22_BAD_TO0D_HASH"

	FIDO_RVT_22_BAD_TO0SIGN_NONCE FDOTestID = "FIDO_RVT_22_BAD_TO0SIGN_NONCE"

	FIDO_RVT_23_POSITIVE FDOTestID = "FIDO_RVT_23_POSITIVE"

	// Voucher tests
	FIDO_TEST_VOUCHER_HEADER_BAD_PROT_VERSION     FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_PROT_VERSION"
	FIDO_TEST_VOUCHER_HEADER_BAD_RVINFO_EMPTY     FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_RVINFO_EMPTY"
	FIDO_TEST_VOUCHER_HEADER_BAD_DEVICEINFO_EMPTY FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_DEVICEINFO_EMPTY"
	FIDO_TEST_VOUCHER_HEADER_BAD_PUBKEY           FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_PUBKEY"
	FIDO_TEST_VOUCHER_HEADER_BAD_CERTCHAIN_HASH   FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_PUBKEY"

	FIDO_TEST_VOUCHER_BAD_HEADER_BYTES  FDOTestID = "FIDO_TEST_VOUCHER_BAD_HEADER_BYTES"
	FIDO_TEST_VOUCHER_BAD_HDR_HMAC      FDOTestID = "FIDO_TEST_VOUCHER_BAD_HDR_HMAC"
	FIDO_TEST_VOUCHER_BAD_PROT_VERSION  FDOTestID = "FIDO_TEST_VOUCHER_BAD_PROT_VERSION"
	FIDO_TEST_VOUCHER_BAD_CHAIN         FDOTestID = "FIDO_TEST_VOUCHER_BAD_CHAIN"
	FIDO_TEST_VOUCHER_BAD_EMPTY_ENTRIES FDOTestID = "FIDO_TEST_VOUCHER_BAD_EMPTY_ENTRIES"

	FIDO_TEST_VOUCHER_ENTRY_BAD_HDRINFO_HASH FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_HDRINFO_HASH"
	FIDO_TEST_VOUCHER_ENTRY_BAD_PREV_HASH    FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_PREV_HASH"
	FIDO_TEST_VOUCHER_ENTRY_BAD_SG_TYPE      FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_SG_TYPE"
	FIDO_TEST_VOUCHER_ENTRY_BAD_SIGNATURE    FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_SIGNATURE"
	FIDO_TEST_VOUCHER_ENTRY_BAD_PUBKEY       FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_PUBKEY"

	NULL_TEST FDOTestID = "NULL_TEST"
)

var FIDO_TEST_LIST_VOUCHER []FDOTestID = []FDOTestID{
	FIDO_TEST_VOUCHER_HEADER_BAD_PROT_VERSION,
	FIDO_TEST_VOUCHER_HEADER_BAD_RVINFO_EMPTY,
	FIDO_TEST_VOUCHER_HEADER_BAD_DEVICEINFO_EMPTY,
	FIDO_TEST_VOUCHER_HEADER_BAD_PUBKEY,
	FIDO_TEST_VOUCHER_HEADER_BAD_CERTCHAIN_HASH,

	FIDO_TEST_VOUCHER_BAD_HEADER_BYTES,
	FIDO_TEST_VOUCHER_BAD_HDR_HMAC,
	FIDO_TEST_VOUCHER_BAD_PROT_VERSION,
	FIDO_TEST_VOUCHER_BAD_CHAIN,
	FIDO_TEST_VOUCHER_BAD_EMPTY_ENTRIES,

	FIDO_TEST_VOUCHER_ENTRY_BAD_HDRINFO_HASH,
	FIDO_TEST_VOUCHER_ENTRY_BAD_PREV_HASH,
	FIDO_TEST_VOUCHER_ENTRY_BAD_SG_TYPE,
	FIDO_TEST_VOUCHER_ENTRY_BAD_SIGNATURE,
	FIDO_TEST_VOUCHER_ENTRY_BAD_PUBKEY,
}
