package testcom

type FDOTestID string

const (
	FIDO_RVT_20_BAD_ENCODING FDOTestID = "FIDO_RVT_20_BAD_ENCODING"
	FIDO_RVT_21_CHECK_RESP   FDOTestID = "FIDO_RVT_21_CHECK_RESP"
	FIDO_RVT_20_POSITIVE     FDOTestID = "FIDO_RVT_20_POSITIVE"

	FIDO_RVT_22_BAD_ENCODING  FDOTestID = "FIDO_RVT_22_BAD_ENCODING"
	FIDO_RVT_22_BAD_SIGNATURE FDOTestID = "FIDO_RVT_22_BAD_SIGNATURE"
	FIDO_RVT_23_CHECK_RESP    FDOTestID = "FIDO_RVT_23_CHECK_RESP"
	FIDO_RVT_23_POSITIVE      FDOTestID = "FIDO_RVT_23_POSITIVE"

	NULL_TEST FDOTestID = "NULL_TEST"
)
