package tools

import fdoshared "github.com/fido-alliance/fdo-shared"

const (
	CFG_DEV_ENV fdoshared.CONFIG_ENTRY = "DEV"

	CFG_ENV_PORT fdoshared.CONFIG_ENTRY = "PORT"

	CFG_ENV_NOTIFY_SERVICE_HOST   fdoshared.CONFIG_ENTRY = "NOTIFY_SERVICE_HOST"
	CFG_ENV_NOTIFY_SERVICE_SECRET fdoshared.CONFIG_ENTRY = "NOTIFY_SERVICE_SECRET"

	CFG_ENV_GITHUB_CLIENTID     fdoshared.CONFIG_ENTRY = "OAUTH2_GITHUB_CLIENTID"
	CFG_ENV_GITHUB_CLIENTSECRET fdoshared.CONFIG_ENTRY = "OAUTH2_GITHUB_CLIENTSECRET"
	CFG_ENV_GITHUB_REDIRECTURL  fdoshared.CONFIG_ENTRY = "OAUTH2_GITHUB_REDIRECTURL"

	CFG_ENV_GOOGLE_CLIENTID     fdoshared.CONFIG_ENTRY = "OAUTH2_GOOGLE_CLIENTID"
	CFG_ENV_GOOGLE_CLIENTSECRET fdoshared.CONFIG_ENTRY = "OAUTH2_GOOGLE_CLIENTSECRET"
	CFG_ENV_GOOGLE_REDIRECTURL  fdoshared.CONFIG_ENTRY = "OAUTH2_GOOGLE_REDIRECTURL"

	CFG_ENV_MICROSOFT_CLIENTID     fdoshared.CONFIG_ENTRY = "OAUTH2_MICROSOFT_CLIENTID"
	CFG_ENV_MICROSOFT_CLIENTSECRET fdoshared.CONFIG_ENTRY = "OAUTH2_MICROSOFT_CLIENTSECRET"
	CFG_ENV_MICROSOFT_REDIRECTURL  fdoshared.CONFIG_ENTRY = "OAUTH2_MICROSOFT_REDIRECTURL"
)

const (
	ENV_DEV  string = "dev"
	ENV_PROD string = "prod"
)
