package testcom

import fdoshared "github.com/fido-alliance/iot-fdo-conformance-tools/core/shared"

type FDOTestID string

const (

	// RVT 20
	FIDO_RVT_20_BAD_ENCODING FDOTestID = "FIDO_RVT_20_BAD_ENCODING"
	FIDO_RVT_20_POSITIVE     FDOTestID = "FIDO_RVT_20_POSITIVE"
	FIDO_RVT_21_CHECK_RESP   FDOTestID = "FIDO_RVT_21_CHECK_RESP"

	// RVT 22
	FIDO_RVT_22_BAD_TO0D_ENCODING              FDOTestID = "FIDO_RVT_22_BAD_TO0D_ENCODING"
	FIDO_RVT_22_BAD_OWNERSIGN_ENCODING         FDOTestID = "FIDO_RVT_22_BAD_OWNERSIGN_ENCODING"
	FIDO_RVT_22_BAD_SIGNATURE                  FDOTestID = "FIDO_RVT_22_BAD_SIGNATURE"
	FIDO_RVT_22_BAD_SIGNATURE_NOT_MATCHING_ALG FDOTestID = "FIDO_RVT_22_BAD_SIGNATURE_NOT_MATCHING_ALG"
	FIDO_RVT_23_CHECK_RESP                     FDOTestID = "FIDO_RVT_23_CHECK_RESP"
	FIDO_RVT_22_BAD_TO0D_HASH                  FDOTestID = "FIDO_RVT_22_BAD_TO0D_HASH"
	FIDO_RVT_22_BAD_TO0SIGN_NONCE              FDOTestID = "FIDO_RVT_22_BAD_TO0SIGN_NONCE"
	FIDO_RVT_23_POSITIVE                       FDOTestID = "FIDO_RVT_23_POSITIVE"

	// DEVT 30
	FIDO_DEVT_30_BAD_ENCODING     FDOTestID = "FIDO_DEVT_30_BAD_ENCODING"
	FIDO_DEVT_30_BAD_UNKNOWN_GUID FDOTestID = "FIDO_DEVT_30_BAD_UNKNOWN_GUID"
	FIDO_DEVT_30_BAD_SIGINFO      FDOTestID = "FIDO_DEVT_30_BAD_SIGINFO"
	FIDO_DEVT_30_POSITIVE         FDOTestID = "FIDO_DEVT_30_POSITIVE"
	FIDO_DEVT_31_CHECK_RESP       FDOTestID = "FIDO_DEVT_31_CHECK_RESP"

	// DEVT 32
	FIDO_DEVT_32_BAD_PROVE_TO_RV_PAYLOAD_ENCODING FDOTestID = "FIDO_DEVT_32_BAD_PROVE_TO_RV_PAYLOAD_ENCODING"
	FIDO_DEVT_32_BAD_ENCODING                     FDOTestID = "FIDO_DEVT_32_BAD_ENCODING"
	FIDO_DEVT_32_BAD_SIGNATURE                    FDOTestID = "FIDO_DEVT_32_BAD_SIGNATURE"
	FIDO_DEVT_33_CHECK_RESP                       FDOTestID = "FIDO_DEVT_33_CHECK_RESP"
	FIDO_DEVT_32_BAD_TO1PROOF_NONCE               FDOTestID = "FIDO_DEVT_32_BAD_TO1PROOF_NONCE"
	FIDO_DEVT_33_POSITIVE                         FDOTestID = "FIDO_DEVT_33_POSITIVE"

	// DOT60
	FIDO_DOT_60_BAD_ENCODING FDOTestID = "FIDO_DOT_60_BAD_ENCODING"
	FIDO_DOT_60_POSITIVE     FDOTestID = "FIDO_DOT_60_POSITIVE"

	// DOT62
	FIDO_DOT_62_BAD_ENCODING        FDOTestID = "FIDO_DOT_62_BAD_ENCODING"
	FIDO_DOT_62_GETOVNEXT_BAD_INDEX FDOTestID = "FIDO_DOT_62_GETOVNEXT_BAD_INDEX"
	FIDO_DOT_62_POSITIVE            FDOTestID = "FIDO_DOT_62_POSITIVE"

	// DOT64
	FIDO_DOT_64_BAD_ENCODING        FDOTestID = "FIDO_DOT_64_BAD_ENCODING"
	FIDO_DOT_64_BAD_EAT_PAYLOAD     FDOTestID = "FIDO_DOT_64_BAD_EAT_PAYLOAD"
	FIDO_DOT_64_BAD_SIGNATURE       FDOTestID = "FIDO_DOT_64_BAD_SIGNATURE"
	FIDO_DOT_64_BAD_NONCE_PROVEDV61 FDOTestID = "FIDO_DOT_64_BAD_NONCE_PROVEDV61"
	FIDO_DOT_64_POSITIVE            FDOTestID = "FIDO_DOT_64_POSITIVE"

	// DOT66
	FIDO_DOT_66_BAD_ENCODING   FDOTestID = "FIDO_DOT_66_BAD_ENCODING"
	FIDO_DOT_66_BAD_ENCRYPTION FDOTestID = "FIDO_DOT_66_BAD_ENCRYPTION"
	FIDO_DOT_66_POSITIVE       FDOTestID = "FIDO_DOT_66_POSITIVE"

	// DOT68
	FIDO_DOT_68_BAD_ENCODING         FDOTestID = "FIDO_DOT_68_BAD_ENCODING"
	FIDO_DOT_68_BAD_ENCRYPTION       FDOTestID = "FIDO_DOT_68_BAD_ENCRYPTION"
	FIDO_DOT_68_BAD_COMPLETION_LOGIC FDOTestID = "FIDO_DOT_68_BAD_COMPLETION_LOGIC"
	FIDO_DOT_68_POSITIVE             FDOTestID = "FIDO_DOT_68_POSITIVE"

	// DOT70
	FIDO_DOT_70_BAD_ENCODING          FDOTestID = "FIDO_DOT_70_BAD_ENCODING"
	FIDO_DOT_70_BAD_ENCRYPTION        FDOTestID = "FIDO_DOT_70_BAD_ENCRYPTION"
	FIDO_DOT_70_BAD_NONCE_PROVE_DV_61 FDOTestID = "FIDO_DOT_70_BAD_NONCE_PROVE_DV_61"
	FIDO_DOT_70_POSITIVE              FDOTestID = "FIDO_DOT_70_POSITIVE"

	// Voucher tests
	FIDO_TEST_VOUCHER_HEADER_BAD_PROT_VERSION     FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_PROT_VERSION"
	FIDO_TEST_VOUCHER_HEADER_BAD_RVINFO_EMPTY     FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_RVINFO_EMPTY"
	FIDO_TEST_VOUCHER_HEADER_BAD_DEVICEINFO_EMPTY FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_DEVICEINFO_EMPTY"
	FIDO_TEST_VOUCHER_HEADER_BAD_PUBKEY           FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_PUBKEY"
	FIDO_TEST_VOUCHER_HEADER_BAD_CERTCHAIN_HASH   FDOTestID = "FIDO_TEST_VOUCHER_HEADER_BAD_CERTCHAIN_HASH"

	FIDO_TEST_VOUCHER_BAD_HEADER_BYTES  FDOTestID = "FIDO_TEST_VOUCHER_BAD_HEADER_BYTES"
	FIDO_TEST_VOUCHER_BAD_HDR_HMAC      FDOTestID = "FIDO_TEST_VOUCHER_BAD_HDR_HMAC"
	FIDO_TEST_VOUCHER_BAD_PROT_VERSION  FDOTestID = "FIDO_TEST_VOUCHER_BAD_PROT_VERSION"
	FIDO_TEST_VOUCHER_BAD_CHAIN         FDOTestID = "FIDO_TEST_VOUCHER_BAD_CHAIN"
	FIDO_TEST_VOUCHER_BAD_EMPTY_ENTRIES FDOTestID = "FIDO_TEST_VOUCHER_BAD_EMPTY_ENTRIES"

	FIDO_TEST_VOUCHER_ENTRY_BAD_HDRINFO_HASH FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_HDRINFO_HASH"
	FIDO_TEST_VOUCHER_ENTRY_BAD_PREV_HASH    FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_PREV_HASH"
	FIDO_TEST_VOUCHER_ENTRY_BAD_SG_TYPE      FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_SG_TYPE"
	FIDO_TEST_VOUCHER_ENTRY_BAD_SIGNATURE    FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_SIGNATURE"
	FIDO_TEST_VOUCHER_ENTRY_BAD_PUBKEY       FDOTestID = "FIDO_TEST_VOUCHER_ENTRY_BAD_PUBKEY"

	NULL_TEST      FDOTestID = "NULL_TEST"
	NULL_TO1_SETUP FDOTestID = "NULL_TO1_SETUP"

	FIDO_TEST_GROUP_SKIP FDOTestID = "FIDO_TEST_GROUP_SKIP"
)

var FIDO_TEST_LIST_RVT_20 []FDOTestID = []FDOTestID{
	FIDO_RVT_20_BAD_ENCODING,
	FIDO_RVT_20_POSITIVE,
	FIDO_RVT_21_CHECK_RESP,
}

var FIDO_TEST_LIST_RVT_22 []FDOTestID = []FDOTestID{
	FIDO_RVT_22_BAD_TO0D_ENCODING,
	FIDO_RVT_22_BAD_SIGNATURE,
	FIDO_RVT_22_BAD_SIGNATURE_NOT_MATCHING_ALG,
	FIDO_RVT_23_CHECK_RESP,
	FIDO_RVT_22_BAD_TO0D_HASH,
	FIDO_RVT_22_BAD_TO0SIGN_NONCE,
	FIDO_RVT_23_POSITIVE,
}

var FIDO_TEST_LIST_DEVT_30 []FDOTestID = []FDOTestID{
	FIDO_DEVT_30_BAD_ENCODING,
	FIDO_DEVT_30_BAD_UNKNOWN_GUID,
	FIDO_DEVT_30_BAD_SIGINFO,
	FIDO_DEVT_30_POSITIVE,
	FIDO_DEVT_31_CHECK_RESP,
}

var FIDO_TEST_LIST_DEVT_32 []FDOTestID = []FDOTestID{
	FIDO_DEVT_32_BAD_PROVE_TO_RV_PAYLOAD_ENCODING,
	FIDO_DEVT_32_BAD_ENCODING,
	FIDO_DEVT_32_BAD_SIGNATURE,
	FIDO_DEVT_33_CHECK_RESP,
	FIDO_DEVT_32_BAD_TO1PROOF_NONCE,
	FIDO_DEVT_33_POSITIVE,
}

var FIDO_TEST_LIST_DOT_60 []FDOTestID = []FDOTestID{
	FIDO_DOT_60_BAD_ENCODING,
	FIDO_DOT_60_POSITIVE,
}

var FIDO_TEST_LIST_DOT_62 []FDOTestID = []FDOTestID{
	FIDO_DOT_62_BAD_ENCODING,
	FIDO_DOT_62_GETOVNEXT_BAD_INDEX,
	FIDO_DOT_62_POSITIVE,
}

var FIDO_TEST_LIST_DOT_64 []FDOTestID = []FDOTestID{
	FIDO_DOT_64_BAD_ENCODING,
	FIDO_DOT_64_BAD_EAT_PAYLOAD,
	FIDO_DOT_64_BAD_SIGNATURE,
	FIDO_DOT_64_BAD_NONCE_PROVEDV61,
	FIDO_DOT_64_POSITIVE,
}

var FIDO_TEST_LIST_DOT_66 []FDOTestID = []FDOTestID{
	FIDO_DOT_66_BAD_ENCODING,
	FIDO_DOT_66_BAD_ENCRYPTION,
	FIDO_DOT_66_POSITIVE,
}

var FIDO_TEST_LIST_DOT_68 []FDOTestID = []FDOTestID{
	FIDO_DOT_68_BAD_ENCODING,
	FIDO_DOT_68_BAD_ENCRYPTION,
	FIDO_DOT_68_BAD_COMPLETION_LOGIC,
	FIDO_DOT_68_POSITIVE,
}

var FIDO_TEST_LIST_DOT_70 []FDOTestID = []FDOTestID{
	FIDO_DOT_70_BAD_ENCODING,
	FIDO_DOT_70_BAD_ENCRYPTION,
	FIDO_DOT_70_BAD_NONCE_PROVE_DV_61,
	FIDO_DOT_70_POSITIVE,
}

var FIDO_TEST_LIST_VOUCHER []FDOTestID = []FDOTestID{
	FIDO_TEST_VOUCHER_HEADER_BAD_PROT_VERSION,
	FIDO_TEST_VOUCHER_HEADER_BAD_RVINFO_EMPTY,
	FIDO_TEST_VOUCHER_HEADER_BAD_DEVICEINFO_EMPTY,
	FIDO_TEST_VOUCHER_HEADER_BAD_PUBKEY,
	FIDO_TEST_VOUCHER_HEADER_BAD_CERTCHAIN_HASH,

	FIDO_TEST_VOUCHER_BAD_HEADER_BYTES,
	FIDO_TEST_VOUCHER_BAD_HDR_HMAC,
	FIDO_TEST_VOUCHER_BAD_PROT_VERSION,
	FIDO_TEST_VOUCHER_BAD_CHAIN,
	FIDO_TEST_VOUCHER_BAD_EMPTY_ENTRIES,

	FIDO_TEST_VOUCHER_ENTRY_BAD_HDRINFO_HASH,
	FIDO_TEST_VOUCHER_ENTRY_BAD_PREV_HASH,
	FIDO_TEST_VOUCHER_ENTRY_BAD_SG_TYPE,
	FIDO_TEST_VOUCHER_ENTRY_BAD_SIGNATURE,
	FIDO_TEST_VOUCHER_ENTRY_BAD_PUBKEY,
}

var FIDO_TEST_TO_FDO_ERROR_CODE map[FDOTestID]fdoshared.FdoErrorCode = map[FDOTestID]fdoshared.FdoErrorCode{
	FIDO_RVT_20_BAD_ENCODING: fdoshared.MESSAGE_BODY_ERROR,

	FIDO_RVT_22_BAD_TO0D_ENCODING:              fdoshared.MESSAGE_BODY_ERROR,
	FIDO_RVT_22_BAD_SIGNATURE:                  fdoshared.INVALID_OWNER_SIGN_BODY,
	FIDO_RVT_22_BAD_SIGNATURE_NOT_MATCHING_ALG: fdoshared.INVALID_MESSAGE_ERROR,
	FIDO_RVT_22_BAD_TO0D_HASH:                  fdoshared.INVALID_MESSAGE_ERROR,
	FIDO_RVT_22_BAD_TO0SIGN_NONCE:              fdoshared.INVALID_MESSAGE_ERROR,

	FIDO_DEVT_30_BAD_ENCODING:     fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DEVT_30_BAD_UNKNOWN_GUID: fdoshared.RESOURCE_NOT_FOUND,
	FIDO_DEVT_30_BAD_SIGINFO:      fdoshared.INVALID_MESSAGE_ERROR,

	FIDO_DEVT_32_BAD_ENCODING:                     fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DEVT_32_BAD_PROVE_TO_RV_PAYLOAD_ENCODING: fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DEVT_32_BAD_SIGNATURE:                    fdoshared.INVALID_MESSAGE_ERROR,
	FIDO_DEVT_32_BAD_TO1PROOF_NONCE:               fdoshared.INVALID_MESSAGE_ERROR,

	FIDO_DOT_60_BAD_ENCODING: fdoshared.MESSAGE_BODY_ERROR,

	FIDO_DOT_62_BAD_ENCODING:        fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DOT_62_GETOVNEXT_BAD_INDEX: fdoshared.INVALID_MESSAGE_ERROR,

	FIDO_DOT_64_BAD_ENCODING:        fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DOT_64_BAD_EAT_PAYLOAD:     fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DOT_64_BAD_SIGNATURE:       fdoshared.INVALID_MESSAGE_ERROR,
	FIDO_DOT_64_BAD_NONCE_PROVEDV61: fdoshared.INVALID_MESSAGE_ERROR,

	FIDO_DOT_66_BAD_ENCODING:   fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DOT_66_BAD_ENCRYPTION: fdoshared.MESSAGE_BODY_ERROR,

	FIDO_DOT_68_BAD_ENCODING:         fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DOT_68_BAD_ENCRYPTION:       fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DOT_68_BAD_COMPLETION_LOGIC: fdoshared.INVALID_MESSAGE_ERROR,

	FIDO_DOT_70_BAD_ENCODING:          fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DOT_70_BAD_ENCRYPTION:        fdoshared.MESSAGE_BODY_ERROR,
	FIDO_DOT_70_BAD_NONCE_PROVE_DV_61: fdoshared.INVALID_MESSAGE_ERROR,

	FIDO_TEST_VOUCHER_HEADER_BAD_PROT_VERSION:     fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_HEADER_BAD_RVINFO_EMPTY:     fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_HEADER_BAD_DEVICEINFO_EMPTY: fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_HEADER_BAD_PUBKEY:           fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_HEADER_BAD_CERTCHAIN_HASH:   fdoshared.INVALID_OWNERSHIP_VOUCHER,

	FIDO_TEST_VOUCHER_BAD_HEADER_BYTES:  fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_BAD_HDR_HMAC:      fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_BAD_PROT_VERSION:  fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_BAD_CHAIN:         fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_BAD_EMPTY_ENTRIES: fdoshared.INVALID_OWNERSHIP_VOUCHER,

	FIDO_TEST_VOUCHER_ENTRY_BAD_HDRINFO_HASH: fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_ENTRY_BAD_PREV_HASH:    fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_ENTRY_BAD_SG_TYPE:      fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_ENTRY_BAD_SIGNATURE:    fdoshared.INVALID_OWNERSHIP_VOUCHER,
	FIDO_TEST_VOUCHER_ENTRY_BAD_PUBKEY:       fdoshared.INVALID_OWNERSHIP_VOUCHER,
}
